### ISSUE TITLE
Save is no go?

### ISSUE THREAD

**Issue by DocSunset** [bboettcher3/mappersession#1]
When I try to save in Webmapper on your sessions feature branch, I get the following exception:

```
Collecting maps from network...
mpr.Object.get_property(Property.TYPE:13) : unhandled char type b'\x00'
mpr.Object.get_property(Property.TYPE:13) : unhandled char type b'\x00'
mpr.Object.get_property(Property.TYPE:13) : unhandled char type b'\x00'
mpr.Object.get_property(Property.TYPE:13) : unhandled char type b'\x00'
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 53142)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/home/tw/tw/repos/webmapper/webmapper_http_server.py", line 101, in do_GET
    found(handlers[command][1])
  File "/home/tw/tw/repos/webmapper/webmapper_http_server.py", line 87, in found
    return self.do_websocket()
  File "/home/tw/tw/repos/webmapper/webmapper_http_server.py", line 123, in do_websocket
    self.do_websocket_8()
  File "/home/tw/tw/repos/webmapper/webmapper_http_server.py", line 258, in do_websocket_8
    decrypt_and_forward(msg[offset:offset+length], key, length)
  File "/home/tw/tw/repos/webmapper/webmapper_http_server.py", line 199, in decrypt_and_forward
    handler_send_command(out, {'msg':m})
  File "/home/tw/tw/repos/webmapper/webmapper_http_server.py", line 350, in handler_send_command
    res = h(vals['args'])
  File "/home/tw/tw/repos/webmapper/webmapper.py", line 258, in on_save
    sessionJson = session.save("", "", [], [])
  File "/home/tw/tw/repos/mappersession/src/mappersession/mappersession.py", line 53, in save
    srcName = (srcSigs[srcIdx].device()[mpr.Property.NAME] +
TypeError: unsupported operand type(s) for +: 'dict' and 'str'
----------------------------------------
```

This may be related to the fact that I was not able to pip install mappersession, getting this error from pip:
```
ERROR: Could not find a version that satisfies the requirement mappersession (from versions: none)
ERROR: No matching distribution found for mappersession
```
So I just cloned the repo and ran webmapper with `PYTHONPATH="$PYTHONPATH:/path/to/mappersession/src" python webmapper.py`...

Problem presumably related to running Arch Linux?

**Comment by bboettcher3** [comment]
hmm, are you able to pip install libmapper on arch linux? I'm using the same wheel building process as libmapper ripped from CI.
For the error that's odd, in mappersession.py could you print out the device name and signal name from:

![image](https://user-images.githubusercontent.com/13266420/202028831-0f3ada71-bf56-4c9b-abb5-87d429900854.png)

It's weird that it's getting the name property as a dict rather than a string so I'm wondering where that's coming from.

**Comment by malloch** [comment]
@DocSunset have you tried saving recently? There have been quite a few changes...

**Comment by DocSunset** [comment]
Just a quick report. I found I was able to `pip install mappersession` in a virtual environment as would normally be expected. Running `python -m mappersession --save` seems to work as well. I think it's very likely this issue is no longer relevant, although I did not test with any devices running on the network.

Great work all involved! Thanks for everything you do.
